# (실행 환경 공통 설정)
# : 개발 환경에 상관 없이 공통으로 적용되는 설정

spring:
  config:
    activate: # 프로필명 설정
      on-profile: idp-jpa

  jpa:
    hibernate:
      # 스키마, 테이블명 UpperCase 허용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl