services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      # root 계정 초기 비밀번호
      MYSQL_ROOT_PASSWORD: todo1234!
      # 초기 생성 데이터베이스
      MYSQL_DATABASE: mysqldb
      # 타임존 설정
      TZ: Asia/Seoul
    volumes:
      - C:/Users/raill/Downloads/tmp/mysql/data:/var/lib/mysql
      - C:/Users/raill/Downloads/tmp/mysql/config:/etc/mysql/conf.d
      - ./mysql_db/init:/docker-entrypoint-initdb.d