# (실행 환경 공통 설정)
# : 개발 환경에 상관 없이 공통으로 적용되는 설정

spring:
  config:
    activate: # 프로필명 설정
      on-profile: dpd-common

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  naverSms: # Naver SMS 설정
    access-key: InputYourAccessKey
    secret-key: InputYourSecretKey
    service-id: ncp:sms:kr:test:test
    phone-number: test
    alim-talk-service-id: ncp:kkobizmsg:kr:test:test