# (실행 환경 local 설정)
# : 로컬 환경 개발자를 위한 환경 설정 = 서버 개발자가 마음껏 사용 가능 (그냥 IDE 를 실행하면 적용)

spring:
  config:
    activate: # 프로필명 설정
      on-profile: dpd-common-local

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  naverSms: # Naver SMS 설정
    access-key: InputYourAccessKey
    secret-key: InputYourSecretKey
    service-id: ncp:sms:kr:test:test
    phone-number: test
    alim-talk-service-id: ncp:kkobizmsg:kr:test:test