# (실행 환경 dev 설정)
# : 개발 환경 개발자들을 위한 환경 설정

spring:
  config:
    activate: # 프로필명 설정
      on-profile: dpd-common-dev

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  naverSms: # Naver SMS 설정
    access-key: InputYourAccessKey
    secret-key: InputYourSecretKey
    service-id: ncp:sms:kr:test:test
    phone-number: test
    alim-talk-service-id: ncp:kkobizmsg:kr:test:test