# (실행 환경 local 설정)
# : 로컬 환경 개발자를 위한 환경 설정 = 서버 개발자가 마음껏 사용 가능 (그냥 IDE 를 실행하면 적용)

spring:
  config:
    activate: # 프로필명 설정
      on-profile: idp-common-local

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  smtp: # SMTP 설정
    host: smtp.gmail.com # SMTP 호스트
    port: 587 # SMTP 포트
    sender-name: InputYourEmailId@test.com # SMTP 계정 아이디
    sender-password: InputYourSenderPassword # SMTP 계정 비밀번호
    time-out-millis: 10000 # 타임아웃 밀리초