global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    static_configs:
      # actuator 요청을 보낼 위치 (ex : ['192.168.0.3:9090'])
      - targets: ['host.docker.internal:8080']