package com.raillylinker.springboot_mvc_template.data_sources.database_sources.db1_main.repositories

import com.raillylinker.springboot_mvc_template.data_sources.database_sources.db1_main.entities.Database1_Template_TestMap
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface Database1_Template_TestMap_Repository : JpaRepository<Database1_Template_TestMap, Long> {
}