global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring_boot_service_1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # actuator 요청을 보낼 위치 (ex : ['192.168.0.3:9090'])
      - targets: ['host.docker.internal:8080']
        labels:
          instance: 'service_1'

  - job_name: 'spring_boot_service_2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # actuator 요청을 보낼 위치 (ex : ['192.168.0.3:9090'])
      - targets: ['host.docker.internal:8080']
        labels:
          instance: 'service_2'