server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  # 동기화 작업을 이루기 위해 promtail이 읽은 마지막 로그 정보를 저장하는 곳
  filename: /tmp/positions.yaml

clients:
  # push할 Loki의 주소
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /logs/*.log